---

- name: "Setting permissions on Harbor common folder......"
  file:
    dest: "{{ harbor_install_dir }}/harbor/common"
    mode: 0750
    group: docker
    recurse: true
  when:
    - not harbor_folder_st.stat.exists or
      (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)

- name: "Setting permissions on nginx folder specifically..."
  file:
    dest: "{{ harbor_install_dir }}/harbor/common/config/nginx"
    owner: 10000
    mode: o+rx
    group: docker
    recurse: true
  when:
    - not harbor_folder_st.stat.exists or
      (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)

- name: Changing registry realm if harbor_registry_realm_protocol is different from harbor_ui_url_protocol
  replace:
    path: "{{ harbor_install_dir }}/harbor/common/config/registry/config.yml"
    regexp: 'realm: (https|http)://(.*)'
    replace: 'realm: {{ harbor_registry_realm_protocol }}://\2'
    backup: true
  when:
    - harbor_behind_proxy is defined
    - harbor_behind_proxy
    - harbor_registry_realm_protocol != harbor_ui_url_protocol

...
