---

- name: create systemd service unit
  template:
    src: "docker-compose.service.j2"
    dest: "{{ systemd_lib_directory }}/harbor.service"
    owner: root
    group: root
    mode: 0644

- name: install dedendency
  package:
    name: "{{ harbor_packages }}"
    state: present

- block:
    - name: create local temporary path
      delegate_to: localhost
      become: false
      file:
        path: "{{ local_tmp_directory }}"
        state: directory
        mode: 0700

    - name: "Downloading Harbor {{ harbor_version }} (offline installer)"
      delegate_to: localhost
      become: false
      get_url:
        url: "{{ harbor_url }}"
        dest: "{{ local_tmp_directory }}/harbor-{{ harbor_version }}.tgz"
        validate_certs: false

    - name: deploy application archiv
      copy:
        src: "{{ local_tmp_directory }}/harbor-{{ harbor_version }}.tgz"
        dest: "/tmp/harbor.tgz"
        mode: 0644

  when:
    - not harbor_folder_st.stat.exists

- name: "creating Harbor directory... ({{ harbor_install_dir }}/harbor)"
  file:
    path: "{{ harbor_install_dir }}"
    state: directory
    mode: 0755
  when:
    - not harbor_folder_st.stat.exists

- name: "uncompressing Harbor installer..."
  unarchive:
    remote_src: true
    src: /tmp/harbor.tgz
    dest: "{{ harbor_install_dir }}"
    mode: 0750
  when:
    - not harbor_folder_st.stat.exists | bool

- name: Creating SSL certs folder
  file:
    path: '{{ harbor_ssl_cert | dirname }}'
    state: directory
    mode: 0750
  when:
    - not harbor_folder_st.stat.exists or
      (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)

- name: Generate self-signed cert with openssl
  command: |
    openssl req
    -newkey rsa:4096
    -nodes
    -sha256
    -keyout '{{ harbor_ssl_cert_key }}'
    -subj '{{ harbor_ssl_self_subject }}'
    -new
    -x509
    -days '{{ harbor_ssl_self_days }}'
    -out '{{ harbor_ssl_cert }}'
  args:
    creates: '{{ harbor_ssl_cert }}'  # don't write over a cert
  when:
    - not harbor_folder_st.stat.exists or
      (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)

- name: Commenting required line on Nginx configuration if harbor_behind_proxy is set
  replace:
    path: "{{ harbor_install_dir }}/harbor/common/templates/nginx/{{ item }}"
    regexp: '(proxy_set_header X-Forwarded-Proto \$\$scheme;)'
    replace: '# \1'
    backup: true
  when:
    - harbor_behind_proxy is defined
    - harbor_behind_proxy
  with_items:
    - "nginx.http.conf"
    - "nginx.https.conf"

# pre-configure

- block:
    - name: copying over harbor.yml
      template:
        src: harbor.yml.j2
        dest: "{{ harbor_install_dir }}/harbor/harbor.yml"
        mode: 0640
      when:
        - not harbor_folder_st.stat.exists or
          (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)

    - name: ensure that prepare script are executable
      file:
        name: "{{ harbor_install_dir }}/harbor/prepare"
        mode: 0750
      when:
        - not harbor_folder_st.stat.exists or
          (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)

    - name: running Harbor installer in {{ harbor_install_dir }}/harbor ...
      become: true
      command: |
        /bin/bash ./install.sh {{ harbor_installer_with | default([]) | join(' ') }} {{ harbor_installer_extra_args }}
      args:
        chdir: "{{ harbor_install_dir }}/harbor"
        creates: '{{ harbor_install_dir }}/harbor/harbor_install_log.txt'
      environment:
        SHELL: /bin/bash
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
        TERM: xterm
      when:
        - not harbor_folder_st.stat.exists or
          (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)

    - name: collect facts about system services
      service_facts:
      register: services_state

    - name: wait 15 seconds for clean startup
      pause:
        seconds: 15
  when:
    - not harbor_folder_st.stat.exists or
      (harbor_folder_st.stat.isdir is defined and not harbor_folder_st.stat.isdir)

- name: wait for health
  uri:
    url: "http://127.0.0.1/api/version"
    validate_certs: false
    method: GET
    status_code:
      - 200
    headers:
      Content-Type: application/json
    body_format: json
    return_content: true
  register: _harbor_version
  until: _harbor_version is succeeded
  ignore_errors: false
  retries: 10
  delay: 10

- name: harbor version
  debug:
    msg: "{{ harbor_version }}"
