---

- include_tasks: prepare.yaml
- include_tasks: install.yml
- include_tasks: configure.yml

# Restart only if we changed the registry realm
- include_tasks: restart.yaml
  when:
    - harbor_behind_proxy is defined
    - harbor_behind_proxy
    - harbor_registry_realm_protocol != harbor_ui_url_protocol

- include_tasks: create_users.yml
- include_tasks: create_projects.yml

- name: remove install package
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/harbor.tgz
    - "{{ harbor_install_dir }}/harbor/harbor.v{{ harbor_version }}.tar.gz"

- include_tasks: service.yml

...
