---

- name: Checking if Harbor is already installed
  stat:
    path: "{{ harbor_install_dir }}/harbor/common/config"
  register: harbor_folder_st

- name: do facts module to get latest information
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - facter

...
